version: '3'

services:
  flask_app:
    container_name: flask_app
    build: . 
    command: python3 app/app.py -host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - SECRET_KEY=secret-key
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}